### PR TITLE
Add COM server to provide BHoM functionality in VBA

### LINKED ISSUE #158: Enable VBA macros/developer mode programming with BHoM references
#### Description:

With more users working in Excel to create templates and macros, it would be hugely beneficial to expose the BHoM libraries/functionality through VBA/macros in Excel. Having had a quick look, it seems like this might only be possible by making the libraries 'COM visible' which I think has wider implications/will be difficult. @awakeman do you have time to look into this/have you already? @michaldengusiak FYI.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #158

Initial version of a COM server that exposes the BHoM in VBA.

### Test files
There is an initial prototype of a File adapter template here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Excel_Toolkit/%23158-BHoMInVBA?csf=1&web=1&e=vC89cV

The first sheet is the template itself. I have also added a sheet for testing pulling and one for testing pushing. The whole thing is still a bit rough but should give a good initial feel for how it works. If nothing works , make sure you have the Excel_UI referenced in your VBA project (the `tlb` file is in ProgramData with all the other assemblies)

### CODE REVIEW

**Comment by al-fisher** [comment]
Hi @adecler - have tested this and can confirm it works.
Great to get this capability in - and might be suitable for very simple wrapping of Push/Pull. But my gut feeling is that for all but the most simple of functionality the "VBA.Adapter" approach is I think is too limiting. The lack of intellisense and access to create and extension methods dealing with `BH.UI.Excel.Object.SetType`, `.SetProperty`  is going to prove frustrating I think. And limit the potential of this feature
Good to explore further the exposing of all methods - as in long run think this with lead to simpler development on both sides
I have added a few comments on the issue which will be good to capture

**Comment by adecler** [comment]
See reply in the issue: https://github.com/BHoM/Excel_Toolkit/issues/158#issuecomment-793285084

**Comment by adecler** [comment]
I have added a SQL Adapter template to the [test file folder](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Excel_Toolkit/%23158-BHoMInVBA?csf=1&web=1&e=geIUS8) following the [PR on the SQL Adapter](https://github.com/BHoM/SQL_Toolkit/pull/2). It ended up being very simple to make by reusing the code from the file adapter. So it might be worth considering at one point centralising some of those reusable VBA functions. 

The one thing I had to fix here was for the case of pushing to a type-strong SQL table. The objects are required to be of that type but were still created as CustomObjects despite having a column for "_t". See commit above for the fix. Ultimately it might be better to refine the template to require the type to be provided alongside the server, database and table instead of a weird `_t` column but that is outside the scope of this PR as the templates will have to be refined anyways.

A feature that might be worth considering though is the handling of cells that contains a reference to a BHoM object. Might be worth planning if this should be part of this PR or kept for a later feature.

**Comment by tg359** [comment]
@adecler, I've had a go at getting this to work on my machine, but think I'm encountering the issue to mention above with the `tlb` file. Build reports as working, though it fails to find the `tlbexp.exe` file which might be why I can't see it in my %ProgramData%. 

image

Strangely, this means I get this helpful error when trying to use your FileAdapter example, and a crash when running the SQLAdapter example.

image

Do you have any suggestions?

**Comment by adecler** [comment]
@tg359 , it looks like you are indeed missing `tlbexp`. This should normally come installed with Visual Studio. 
What version of VS are you using ? 
Can you check if this folder exists (version numbers may vary) ? `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools`

**Comment by michaelhoehn** [comment]
@adecler I was testing yesterday and experiencing the same issues as @tg359. I can confirm the TlbExp.exe file is there in the Windows SDK. I'll keep digging to see what's going on. 

image

**Comment by adecler** [comment]
Thanks @michaelhoehn , can you confirm the version of Visual Studio you are using ?

**Comment by michaelhoehn** [comment]
@adecler ~~I'm running VS Community 2019 v16.8.31005.135~~

Just updated to v16.9.3

**Comment by adecler** [comment]
Thanks @michaelhoehn, @tg359  , this was indeed a problem specific to Visual Studio 2019. 
I have committed a change that should fix the problem (it did for my newly installed version of 2019 at least 😄 ).
Let me know if that work for you.

**Comment by adecler** [comment]
I have added a basic wiki page on how to use the BHoM in VBA here: 
https://github.com/BHoM/Excel_Toolkit/wiki/Using-the-BHoM-in-VBA

**Comment by adecler** [comment]
@IsakNaslundBh , as discussed I have added the support for enums. I ended up supporting both setting enums properties with a string and the creation of enums as individual objects. You can find the documentation and examples of it in the wiki: https://github.com/BHoM/Excel_Toolkit/wiki/Using-the-BHoM-in-VBA#creating-an-enum

The ability to pass enums as strings was added to the Reflection engine so you will need to use [this PR](https://github.com/BHoM/BHoM_Engine/pull/2457) if you want to use that.

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@FraserGreenroyd , it looks like the Excel toolkit is still on the old checks. I have ran the checks for copyrights and for the installer but that generated new checks with green ticks instead of validating the existing ones.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by adecler** [comment]
I have added a `Verify_VBA.xlsm` file in the test folder provided in the first comment. This file runs a series of unit test on the different parts of the COM interface. The tests on the adapter are a bit light because it is not possible to isolate the push from the pull without relying on additional files or an external database that might change (and we cannot use mocks in this context). I think it is fine though since we have the other two templates files that are purely focusing on using the (File and SQL) adapters.

Here's how the unit test file looks right now:

image

**Review by tg359 — DISMISSED** [review]
I managed to get objects to reference from the sheet, and create them in VBA - then push these into SQL 👍 

There were a few issues along the way, so just noting these here, but in terms of functionality it works and I'd be happy to use it as is.
- Return from FileAdapter isn't as expected so the VBA code throws an error after pushing objects into a file.
- When looping though a range, the BHoM objects referenced on a sheet are created and appended to a collection, but seem to reset to default values upon hitting the `NEXT` in that loop, so only the last object in the collection retains its values. This doesn't seem to happen when creating the object from values inside the VBA loop. Here's the file where this issue was encountered - [SampleData.zip](https://github.com/BHoM/Excel_Toolkit/files/6324717/SampleData.zip)

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@FraserGreenroyd, the null-handling check is acting up again. I t would be great if it was only checking null handling of modified files instead.

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@tg359 , I have fixed a couple of minor compliance issues. This dismissed your previous review.. Do you mind re-approving this PR ?

**Review by tg359 — APPROVED** [review]

**Comment by adecler** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2386565658

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2386565658

**Pull request merged**
