### PR TITLE
Update CSProj for TLB deployment

### LINKED ISSUE #294: Excel_UI.tlb is not part of the installer
#### Description:
After installing a new alpha Excel_UI.tlb does not exist in the Assemblies folder. 

#### Steps to reproduce:
Install current alpha and check Assemblies folder.

#### Expected behaviour:
Excel_UI.tlb should exist in the Assemblies folder after installation of the BHoM.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #294

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by adecler — COMMENTED** [review]
I am a bit hesitant on this one.
The change means we are explicitly targeting Windows 10 and .NET framework 4.8 while neither of them is a dependency of this toolkit.  
I wonder if it wouldn't make more sense to set the environment variable directly on the VM or to have a separate build config.

**Comment by FraserGreenroyd** [comment]
> I am a bit hesitant on this one.
> The change means we are explicitly targeting Windows 10 and .NET framework 4.8 while neither of them is a dependency of this toolkit.
> I wonder if it wouldn't make more sense to set the environment variable directly on the VM or to have a separate build config.

Do you know which environment variable we need then, I tried looking at that before going for this solution but couldn't find a suitable option, if you've got one I'm happy to give it a try on the VM.

**Comment by adecler** [comment]
Use the system PATH variable. IT's likely that VS has its own path variable. Which would explain why it works when compiling via VS but fails via the bot (that uses MsBuild).

**Comment by FraserGreenroyd** [comment]
Closing this PR as the VM is now working by the looks of it, and will be fully confirmed with a proper installer created in the morning :smile:

**Pull request closed without merging**
