### PR TITLE
Handle casting of items in lists and trees

### LINKED ISSUE #314: Object requiring a list of enums for property throws null error
#### Description:

I'm trying to create an `EnvironmentalMetric(Field, List<Phases>, Quantity, Name)` in excel, and I'm getting an Excel null error when I create with more than one Phase using the `LifeCycleAssessmentPhases` enum. 

I've tried multiple methods including using the `Condense()` and also using a range (i.e. G5:G7). I'm only able to successfully create this object by using a single phase enum for this property, which is undesirable as metrics need to be able to host multiple phases when needed. 

I don't think this relates 100% to this issue https://github.com/BHoM/Excel_Toolkit/issues/311 but could possibly shed some light on a particular hurdle. 

#### Steps to reproduce:

Follow the above outline with the sample workbook. 

#### Test file(s):

[Sample Workbook](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Excel_Toolkit/Issue%20314/Multi%20enum%20property%20error.xlsx?d=w3f6321382766494bb5a55ee81ce1b3d8&csf=1&web=1&e=bo6NMd)

FYI @kayleighhoude

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #314

Casting of types that are handled differently by Excel (e.g. dates, enums, etc.) was only covered for cells containing a single element. This PR fixes that.

### Test files
Same as provided in the issue: [Sample Workbook](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Excel_Toolkit/Issue%20314/Multi%20enum%20property%20error.xlsx?d=w3f6321382766494bb5a55ee81ce1b3d8&csf=1&web=1&e=bo6NMd)

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed the code changes and they make sense based on the issue.

Have not been able to test with the workbook as I've been having Excel problems 🥳 am happy to try again tomorrow if desired @adecler but not sure if this is needed soon for your work in zero-code tools hence have done a code-review as the large chunk of moved code is now in a separate method and called by areas that appear to need it, hence I'm happy for this to go to alpha tonight if desired.

**Comment by adecler** [comment]
Thanks @FraserGreenroyd ,

I prefer to wait for @michaelhoehn 's review before merging.

**Review by michaelhoehn — APPROVED** [review]
I've tested this and it's working great! LGTM

**Pull request merged**
