### PR TITLE
Add BHoM Methods to context Menu

### LINKED ISSUE #45: Excel_Toolkit : Adding BHoM navigation to Context Menu
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by awakeman**
Fixes #45 

image

### CODE REVIEW

**Comment by awakeman** [comment]
Relies on BHoM/BHoM_UI#55

**Comment by adecler** [comment]
Great! That's a good start.
- [ ] Can you also add the rest of the components to match what we have in GH and Dynamo ? We are missing quite a few at the moment.
- [ ] Can you also add the context menu to the formula bar and the Ctrl-Shift+B global menu? This one can be a separate issue/PR but I don't see an issue raise for it so thought  I would remind you here.

On a side note, I only have 'Adapter' and 'Engine' showing up on my version. I haven't had the time to look more into it so not the most useful comment on its own since it seems to be working for you. @al-fisher , @rwemay , do you have the same problem?

image

**Comment by awakeman** [comment]
>Can you also add the rest of the components to match what we have in GH and Dynamo ? We are missing quite a few at the moment.

That's probably due to the ones that only have a single method (Pull, Push, Delete, etc.) don't place anything in their `itemTree` so don't ordinarily make any menu entries. I did think of this but wasn't sure whether it would be in scope for this. It will involve some bespoke Excel code but should remain pretty thin.

>Can you also add the context menu to the formula bar

One reason I avoided this for now is because I think it is likely to be tricky to know what keys to send (whether or not to prefix with `=`) based on whether or not the user is in the middle of a formula or has a blank cell. I wasn't (easily) able to find API access to the currently typed string in the Formula Bar. Raised #57.

>and the Ctrl-Shift+B global menu?

 Raised as #56

**Comment by awakeman** [comment]
image

**Comment by adecler** [comment]
Thanks,

I am missing a few in the Engine (`Explode`, `ToJson` and `SetProperty`). To the exception of Explode, I can see you have added them in the code so I guess this is a similar problem than for the oM not showing up in my menu. @al-fisher , @rwemay , can you check what happen on yours ?

Also, any reason for not adding the search in the context menu ? Was that because it will be provided by the global search anyway?

**Comment by awakeman** [comment]
We'll need to investigate why `ToJson` and `SetProperty` aren't showing for you, like with your previous comment, Works For Me™. Well, `SetProperty` is showing as its underlying method `PropertyValue(BHoMObject, String, Object)` so maybe I could force it to be named `SetProperty`

`Explode` is the one Engine method that is still not using the `BHoM_UI` implementation, though I suppose for now I could add a menu entry for it manually.


>Also, any reason for not adding the search in the context menu ? Was that because it will be provided by the global search anyway?

Precisely this, using the current implementation there would be a number of separate Search boxes. I am considering as part of #56 to also add the `GlobalSearch` to the context menu.

**Comment by awakeman** [comment]
Addressed those now. The single method ones use their friendly name (e.g. `Set Property`) and `Explode` forwards to the bespoke Excel implementation of `Explode`.

**Comment by IsakNaslundBh** [comment]
Having the same problem as @adecler . Only Engine and Adapter is showing up in the menu. Also, this makes the rest of the toolkit malfunction for me. Non of the inline methods are showing up any more on this branch. Switching to master everything still works fine.

**Comment by awakeman** [comment]
I believe it's solved by 41f9e47, @IsakNaslundBh @adecler could you confirm,

**Comment by IsakNaslundBh** [comment]
Things seem to be working on my end now.

**Comment by adecler** [comment]
The problem of PropertyValue was fixed in https://github.com/BHoM/BHoM_UI/pull/57
Can you update your repo and check again?

**Comment by adecler** [comment]
oM is now showing up. Same as for the other sections though, quite a few components missing.

image

**Comment by awakeman** [comment]
The necessary functionality for `CreateCustom`, `CreateEnum` and `CreateData` hasn't been implemented yet, see #23 for the latter two. I'll raise an issue to add `CreateCustom` too but I don't consider it in the scope of this issue/PR, it should be evident that once implemented the changes introduced by this PR will mean they will be added to the context menu without additional work.

**Comment by awakeman** [comment]
@al-fisher, @IsakNaslundBh agreed it would be more obvious that the menu items are BHoM related if they were prefixed with `BH.` (`BH.Adapter`, `BH.Engine`, `BH.oM`).

image

**Comment by awakeman** [comment]
Reverted to using the caller name (derived from method name) as opposed to a customised friendly name in light of BHoM/BHoM_UI#57.

**Review by IsakNaslundBh — APPROVED** [review]
This works well on my machine.

Agreed that changes requested by Arnaud will be dealt with in upcoming issues.

**Pull request merged**
