### PR TITLE
New features for the Building Performance Form

### LINKED ISSUE #302: Store extra properties set by VBA in CustomData
#### Description:
Extra properties set on objects from VBA were ignored until now. It would be more robust to store them in CustomData.
In a similar fashion, properties in Custom data should now be exposed to VBA.

### LINKED ISSUE #303: Expose the Remove adapter method to VBA

### LINKED ISSUE #304: Provide a new COM Dictionary class for VBA

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #302 
Closes #303
Closes #304

All the features are implemented to support required functionalities for the Building Performance Excel form.

### Test files
https://burohappold.sharepoint.com/:x:/r/sites/Direction/designtechnology/RandDWishlist/00229_BuildingPerformance_DataEntryTemplate/BuildingPerformanceForm2.xlsm?d=waa06976ed94c4ce2823c19904a293234&csf=1&web=1&e=wHEK3T

### Changelog
- Store extra properties set by VBA in CustomData
- Expose the Remove adapter method to VBA
- Provide a new COM Dictionary class for VBA

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Review by tg359 — DISMISSED** [review]
Reviewed for functionality as part of the PR for the Building Performance Excel form.

All functionality works when using that form 👍

**Review by FraserGreenroyd — DISMISSED** [review]
Copy local needs to be resolved.
PR title needs to be improved.
I will then dispensate the remaining issue on project compliance and look into why it's flagged it

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@FraserGreenroyd , I have changed the copy local to false (as discussed before, I don't see those as necessary anymore but fine). Can you check that you are happy ?

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@tg359 , I have made the change requested by Fraser. All same functionality as before, just a referenced dll not being copied locally to the build folder anymore (archaic concern that is now irrelevant). Can you re-approve please ?

**Review by tg359 — APPROVED** [review]

**Pull request merged**
