### PR TITLE
Provide a COM adapter constructor that takes fileName as Input

### LINKED ISSUE #307: Make it possible to create an adapter without the need to provide the full namespace
#### Description:
Right now, it is only possible to create an adapter if the exact full type name is provide.
In general, there will be no risk of clashing between namespace when providing the adapter name. So being able to akip the namespace would be convenient.

### LINKED ISSUE #308: Calling methods with list arguments (other than List<object>) is not working
#### Description:
As per title

#### Steps to reproduce:
You can try this VBA code for example

```vba
Dim inputs As Excel_UI.Collection
Set inputs = New Excel_UI.Collection
Call inputs.Add(name)
Call inputs.Add(number)
Call inputs.Add(cases)
Call inputs.Add(factors)
            
Dim combination As Excel_UI.Object
Set combination = bhom.CallMethod("BH.Engine.Structure.Create.LoadCombination", inputs)
```

### LINKED ISSUE #309: Provide a COM adapter constructor that takes fileName as Input
#### Description:
This is to expose teh functionality created in https://github.com/BHoM/BHoM_Adapter/pull/301

### PR DESCRIPTION
**Pull request by adecler**
### Depends on

https://github.com/BHoM/BHoM_Engine/pull/2615
 

### Issues addressed by this PR

Closes #307 
Closes #308 
Closes #309 

This provides a few fixes that enable our Loadcases and [Load combinations tool](https://burohappold.sharepoint.com/:f:/r/sites/Direction/designtechnology/RandDWishlist/00270_Load%20Case%20and%20Combinations%20Excel%20Tool?csf=1&web=1&e=HK8nRq) to work through the VBA COM interface.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/Direction/designtechnology/RandDWishlist/00270_Load%20Case%20and%20Combinations%20Excel%20Tool?csf=1&web=1&e=HK8nRq

### CODE REVIEW

**Review by IsakNaslundBh — COMMENTED** [review]
Have tested with the linked script, and only the last Loadcase is pushed to the software on the Loadcase sheet.

On the combinations sheet, I get a vba error when trying to push (unhelpful): 
image

Same behaviour with Robot, Etabs18 and GSA.

The adapter creation works as expected though, hence unsure if this is a problem with the vba rather than with the c# code in this PR.

**Comment by adecler** [comment]
Thanks @IsakNaslundBh , 

It might be worth doing a session together to look into this as I don't currently have a license for any of the structural analysis software. So a bit difficult for me to test/debug fully. I did test up to the point of the structural adapters were receiving the full list of cases/combinations as input for their pull but that's as far as I managed to go.

**Comment by adecler** [comment]
@IsakNaslundBh , I finally had time to fix the issue with pushing load combinations. As discussed before, the issue was linked to the ability of the engine to set a `FragmentSet` property from a list of objects.
You can find the PR with the fix [here](https://github.com/BHoM/BHoM_Engine/pull/2615).

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check project-compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Review by IsakNaslundBh — DISMISSED** [review]
Works fine with provided test script

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3564339452

**Review by IsakNaslundBh — APPROVED** [review]
Have tested the initial steps of this PR, but not the enumeration.

Leaving an approval here as the Enumeration stuff needs to be tested and merged separately before this PR is merged anyway (check installer will fail) But will add a do not merge tag as well until all is ready.

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
