### PR TITLE
Set ProjectIdEvent with FileId

### LINKED ISSUE #367: Analytics Pop-up appears though Excel Title Info is filled out
#### Description:

Analytics Pop-up appears though Excel Title Info is filled out 

#### Steps to reproduce:

Fill in Title info, call BHoM method

### PR DESCRIPTION
**Pull request by travispotterBH**
### Issues addressed by this PR

Analytics Pop-up should not appear if Excel's Info --> Title property is filled out prior to BHoM method call. 

Closes #367 

Project ID Event is set with appropriate file id to allow LINQ filtering to collect the event from other logged events.
Project Id gets set before execution of pop-up window if project information project number is set.

### Changelog

- Added FileId to ProjectIDEvent

### CODE REVIEW

**Comment by travispotterBH** [comment]
@BHoMBot  check required

**Review by FraserGreenroyd — APPROVED** [review]
Code changes make sense and resolve the issue we've been chasing down.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by travispotterBH** [comment]
@BHoMBot check versioning

**Comment by travispotterBH** [comment]
@BHoMBot  check versioning
@BHoMBot check ready-to-merge

**Comment by travispotterBH** [comment]
@BHoMBot check copyright-compliance

**Pull request merged**
