### PR TITLE
Excel toolkit #123 nuget dependencies

### LINKED ISSUE #123: Excel_Toolkit: Use NuGet for reference to external dlls
#### Description:
Direct links to locally installed dlls need to be replaced by references through NuGet packages.
This is required so we can set up continuous integration on AppVeyor (where Excel is obviously not installed)

It might be worth considering using NetOffice as it supports versions 2010, 2013 and 2016.

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #123 

Moved to using NetOffice to interface with MS Office COM API for greater compatibility and the ability to use NuGet packages to fulfil the dependency.

### Test files

Please run through the sample workbooks in here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/_Macro?csf=1&e=Bv6sbK

### Changelog
- Migrated to NetOffice for MS Office COM interaction.

### CODE REVIEW

**Comment by adecler** [comment]
1. AppVeyor is happy

1. Here's the testing I have done:
    - Create a Point and a Node  -> seems to be working
    - Create a custom object using CreateCustomcaller.CreateCustom  -> couldn't figure out the inputs
    - Try to explode the objects I created -> couldn't get it to work
    - Open the two examples you provide above -> files are mainly empty so not sure what to do with them

So
- Can we get a wiki (see https://github.com/BHoM/Excel_Toolkit/issues/15) ?
- Someone that have used the example files you provide needs to test this before approving

**Comment by awakeman** [comment]
Sorry, looks like there was an issue with one of the files I uploaded to that link. They should now be correct. I'll see if I can get someone else to test though.

Explode is broken, fixed by #131.

For future reference `CreateCustom` works like `CreateDictionary` and takes a list of keys and values.

**Comment by jdarcyBHE** [comment]
Tested Multi-storey template test script:

1. Pushing BHoM Objects works into Robot
2. Pulling BHoM Objects back to apply loading fails, on this PR.
3. Tested script on master branch both push and pull work.

**Comment by awakeman** [comment]
@jdarcyBHE as shown yesterday there was a little hack I needed to add to make it all work given a bug in the latest version of one of the dependent toolkits, if you could take another look today that'd be great.

**Review by jdarcyBHE — COMMENTED** [review]
Testing Mulitstoreytoolkit:

Push and Pull both work, it has highlighted a couple of errors in the Mulitstoreytoolkit, issue will be raised by @awakeman.

**Review by jdarcyBHE — COMMENTED** [review]
Tested ROI Library template, updates on sharepoint_toolkit:
Template works successfully files pulled from sharepoint correctly.

**Comment by adecler** [comment]
@jdarcyBHE, are you planning to do further tests or are you happy for me to merge this PR?

**Comment by jdarcyBHE** [comment]
@adecler no I am done with testing, merge away.

**Comment by al-fisher** [comment]
Hey @jdarcyBHE - if you are happy and reviewed this can you formally "Approve".
We can then merge. Thanks 👍

**Review by al-fisher — APPROVED** [review]
Tested now - and switching to nugets looks good.
Approve to merge

**Pull request merged**
