### PR TITLE
Treat blank references as default when given for list input

### LINKED ISSUE #90: Excel_Toolkit: Inputting a null in an in cell formula generates a list
Inputting a null/empty variable between commas in an in cell formula creates a list (for list input) rather than a null which when it gets passed to methods causes errors where a default/override is checking for null only. 

This might relate to an issue @IsakNaslundBh  raised in that an empty cell returns a null when the cell is empty (maybe). 

In any case, I think if a variable in an in cell formula is blank, it should create a null rather than an empty list(?)

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #90 

### Test files
[list-test.xlsx](https://github.com/BHoM/Excel_Toolkit/files/3206780/list-test.xlsx)

### CODE REVIEW

**Comment by rwemay** [comment]
No test scripts, can you please add links to test scripts so this can be tested ASAP.

**Comment by obosob** [comment]
[list-test.xlsx](https://github.com/BHoM/Excel_Toolkit/files/3206767/list-test.xlsx)

The attached excel file will fail to create the Ray object on master but will succeed on this branch.

**Comment by awakeman** [comment]
[list-test.xlsx](https://github.com/BHoM/Excel_Toolkit/files/3206780/list-test.xlsx)

The following excel file will fail to create a `Ray` on master but will succeed on this branch.

**Comment by FraserGreenroyd** [comment]
Adding @michaldengusiak as a reviewer to help share the load with @IsakNaslundBh

**Review by michaldengusiak — APPROVED** [review]
works as expected... 
before
image
after
image


ps. when starting excel I have this message, this is new for me I never seen this before...I click no and worked fine...
image

**Comment by awakeman** [comment]
Just a note on your p.s., that happens if the the addin caused excel to crash (or, more likely, you killed excel when the addin was doing something), so it provides a mechanism to stop it from loading as a safety against addins that repeatedly crash excel.

**Pull request merged**
