### PR TITLE
Log file id and file path

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2312
https://github.com/BHoM/BHoM_UI/pull/370

   
### Issues addressed by this PR
Provide changes required for fileName and project code to be saved by analytics.

### Test files
Will be tested alongside the [BHoMAnalytics PR](https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/16)

### Additional comments
Excel workbooks don't have a Guid so I inject one in their custom properties the first time it is requested.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by rolyhudson** [comment]
Followed the equivalent steps for testing as per https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/16. All LGTM - I get the log file. I see the project and file name logged. Happy to approve once @al-fisher or @adecler confirm the entry has been found in the BHoMAnalytics database.

**Comment by adecler** [comment]
Thanks @rolyhudson , just to confirm:
- the project code you used was `project_rolyExcel`
- the files you used were `analyticsPR.xlsx` and `analyticsPR.gh` (not writing the whole file path here for obvious reasons)

**Comment by rolyhudson** [comment]
@adecler - sorry I should been clearer 
With GH
- project code: `project_roly`
- file `analyticsPR.gh`

With Excel
- project code: `project_rolyExcel`
- file `analyticsPR.xlsx`

**Review by al-fisher — CHANGES_REQUESTED** [review]
Capturing and logging the ProjectCode and File names as expected. 
There is however an issue with using numerical data as input to `SetProjectCode`. Agree input must ultimately be of type string - most flexible - however in the Excel UI we might need to address some casting from number to text so it works intuitively for any input type. See screen shot below:

row 1 is numerical data explicitly pasted in as text
row 2 is naturally a string
row 3 is a standard number in excel
row 4 is a number formatted as text - which also fails



image

**Comment by al-fisher** [comment]
One way to address the above might be to have an explicit component in the Excel BHoM UI ribbon? Which could potentially solve two problems. 
Can in this component handle casting, as well as making the component more easily findable - as is a "special" UI component after all.

**Comment by adecler** [comment]
@al-fisher , this is an issue with our data accessor in Excel that is quite outside the scope of this PR. I have raised a separate issue for that here: https://github.com/BHoM/Excel_Toolkit/issues/281.

Since providing a number for project id is going to be our default behaviour, however, I added a fix for that specific case in this PR.

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by al-fisher** [comment]
Thanks @adecler this is working well now for combinations of text/numbers
image

**Review by al-fisher — CHANGES_REQUESTED** [review]
@adecler noticed a slight inconsistency of the `FileName` formatting across UIs 

The format of the `FileName` is different in the Excel.log compared to the Grasshopper.log for files in Onedrive/synced Sharepoint sites.

In Excel the `FileName` is stored as the actual URL - whereas in Grasshopper it is the local (synced) directory. For only local files format is same for both.

Either format is fine tbh I would say - but thinking this inconsistency between formats across UIs can be a bit annoying for processing. Thinking may be best to address here at point of capture and logging rather than handling reformatting/doing data wrangling and reformatting downstream.

**Comment by adecler** [comment]
@al-fisher , to be honest, I don't really have much choice in the matter 😅 . Excel only gives me 3 options (well, 2 more than Dynamo and GH to be honest):
- workbook.FullName
- workbook.FullNameURLEncoded
- workbook.Path

I currently use `FullName` but all 3 are giving me the same anyways (well, `Path` is not including the file name)

**Review by al-fisher — APPROVED** [review]
@adecler - as discussed makes sense.

**Pull request merged**
