### PR TITLE
Add support for DBNull when converting VBA nulls to C# nulls

### LINKED ISSUE #299: Enable passing nulls to methods in VBA
#### Description:

Trying to pass a null to a method/constructor that should be able to handle it, such as RobotCOnfig to the constructor:

image

Gives the following in the c# code:

image

Good if nulls could be allowed to be passing as accepted argument to reference type inputs, especially those that allow nulls as default values.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #299

See issue

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Excel_Toolkit/%23299-SupportForVbaNulls?csf=1&web=1&e=UTZf8E

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
This works fine my end!

**Pull request merged**
