### PR TITLE
Excel_Toolkit: Don't enable all BHoM functionality on excel open and Ribbon UI

### LINKED ISSUE #130: Excel_Toolkit: Add UI to Excel to replicate Grasshopper icons/UI, and add an 'Load BHoM' option
#### Description:

Load BHoM option would allow people to toggle whether BHoM loads by default when loading Excel, or load manually from the UI. If a Workbook with BHoM inside is opened, BHoM should force-load.

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #130 

Adds a button to the ribbon to enable BHoM, registration of BHoM methods is deferred until this point. Once loaded, the ribbon shows all components as a navigable menu.

If a BHoM workbook (a workbook that the BHoM has been used from) is opened, the BHoM is loaded whilst opening that file.

image

image

### Test files
Please test for regression with files in https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Excel_Toolkit/_Macro?csf=1&e=JXNE7u and any other scripts you may use regularly.

### Changelog

- No longer register excel functions on start
- Add Ribbon UI

### CODE REVIEW

**Comment by rwemay** [comment]
Great to see this, thanks! I will struggle to review I'm afraid. @michaldengusiak might be interested?!

**Comment by awakeman** [comment]
This also closes #141 by nature of the changes made so makes #142 irrelevant, will close that PR in favour of this one.

**Review by michaldengusiak — CHANGES_REQUESTED** [review]
ok here is my test ...
1. I :sparkling_heart: love that finally we can use BHoM always and is not affecting excel that do not contains BHoM   ...Hureeyyyyy 
2. I tested to create pull revit script using new Ribbon but it did not work for me, problem is with `FilterRequest `see video

BHoMexcel

I did it again `FilterRequest ` manually using` Ctrl + Shift +B `and realized that in Ribbon we still use `Query ` name but it should be request, also there are different formula if we select from Ribbon or type:
image

working when we use  C`trl + Shift +B `
image

using Ribbon does not work
image

what is the difference?

**Comment by al-fisher** [comment]
On initial testing .. going to echo @michaldengusiak comment and ❤️ above!! 
Love this new interface! 👍  Great stuff @awakeman !
🚀🚀🚀🚀

**Comment by awakeman** [comment]
@michaldengusiak that should work now.

**Review by michaldengusiak — DISMISSED** [review]
Absolutely great!!! :innocent:

thanks you :art:

image

**Comment by awakeman** [comment]
Just made a change to lazily load the menus so startup is even faster. Since that is important for this PR I pushed. Does mean it needs checking again though. Sorry @michaldengusiak.

**Review by michaldengusiak — APPROVED** [review]
works great and now for me  3 sek faster

image

**Comment by awakeman** [comment]
Smashing, thanks @michaldengusiak for all the help. :ship: :rocket:

**Pull request merged**
