### PR TITLE
Fix enum loading bug

### LINKED ISSUE #363: Enums Not Updating
#### Description:
When new items are added to enums, existing workbooks do not update the enum, where new workbooks show the entirety of the entries in the enum.

EnumNotUpdating

@travispotterBH @michaelhoehn not sure if you have seen this issue as well

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #363 

### Test files
N/A - test steps instead:

 1. Create an Excel file with a BHoM enum object.
 2. Save the file
 3. Change the enum which was added to the Excel sheet by adding or removing a value
 4. Recompile the enum
 5. Reopen the Excel file previously made
 6. Verify the dropdown is now updated with the changed values - this did not happen on main

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by travispotterBH — APPROVED** [review]
Tested on a call with Fraser.  Looks good to go.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
