### PR TITLE
Add Help buttons to ribbon to link to wikis and bhom.xyz

### LINKED ISSUE #147: Excel_Toolkit: Add help/documentation links from the UI
#### Description:

There should be some buttons on the UI that give users access to the BHoM documentation (e.g. windows help file, bhom.xyz, BHoM wiki and Excel wiki)

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #147 

Adds 3 buttons that go to the following URLs: 
- https://github.com/BHoM/Excel_Toolkit/wiki
- https://github.com/BHoM/documentation/wiki
- https://bhom.xyz

### Test files
Visually confirm but please test with test library files and your own and check UI functionality (https://github.com/BHoM/Excel_Toolkit/wiki/Testing-checklist has been started to cover things that need checking).

### Changelog

- Add help buttons to Ribbon

### Additional comments

Please check the labels, icons and wording are appropriate and let me know if you'd like them changed.

image

### CODE REVIEW

**Comment by awakeman** [comment]
Note: There is tooltip text, please review it too.

**Review by michaldengusiak — APPROVED** [review]
test:
Mouse
1.Selection - passed
2.Dismissal - passed
Mouse
1.Selection - passed
2.Dismissal - passed

web links works fine...
thanks

**Review by michaldengusiak — APPROVED** [review]
test:
Mouse
1.Selection - passed
2.Dismissal - passed
Mouse
1.Selection - passed
2.Dismissal - passed

web links works fine...
thanks

**Comment by michaldengusiak** [comment]
ps. I would suggest renaming to Excel_Toolkit Wiki, so it is clear between toolkit and generic BHoM
image

**Pull request merged**
