### PR TITLE
Consolidate and Update ExcelDna Nuget packages

### LINKED ISSUE #88: Excel_Toolkit: Nuget packages have mismatched versions.

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #88 

Updated the nuget packages as there were some version conflicts between the versions between Adapter and Engine.

### CODE REVIEW

**Comment by rwemay** [comment]
How do we test this and get it merged? @IsakNaslundBh is marked as a reviewer, is it the case for Isak to just check the nuget package versions, or..?

**Comment by awakeman** [comment]
yeah, just a case of someone checking the nuget versions and checking it builds and runs as before. It's just a bit of houskeeping.

**Comment by rwemay** [comment]
This only builds for me if I restore nuget packages on the solution. Assume that's OK?

**Comment by awakeman** [comment]
yeah, that should be the case.

**Review by rwemay — APPROVED** [review]

**Pull request merged**
