### PR TITLE
Add internalise button to all cell-related context menus

### LINKED ISSUE #149: Internalise Data not working in some cases
#### Description:

As above. 

#### How to replicate:

 - ~~Create a BHoM object, right click whilst in page break view, and note that the internalise data is not visible in the context menu.~~
 - When data is internalised (in normal view) the hidden sheet is created, however, the cell with the internalised data retains the formula/original entry, such that there is no reference to the internalised data. 

#### Expected behaviour:

 - ~~Internalise data should always be visible in context menu when BHoM is loaded/initialised.~~ 
 - When data is internalised, the cell contents should be replaced such that upstream/referenced changes in the spreadsheet do not cause the cell with internalised data to lose reference.

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #149 

Adds the "Internalise Data" option to all views and contexts (tables and regular cells) 

### Test files

Please follow https://github.com/BHoM/Excel_Toolkit/wiki/Testing-checklist and run through existing excel files to check for regressions.

### Changelog

- Added "Internalise Data" button to all cell-related context menus

### CODE REVIEW

**Comment by awakeman** [comment]
NOTE:

#149 also raises that internalise wasn't functioning properly that i cannot reproduce. We need to be sure whether or not that is a real issue because as of yet there is no change to address that (since I couldn't reproduce to find the cause).

**Comment by awakeman** [comment]
Added reviewers, if anyone has time would be good to get this reviewed ASAP, thanks.

**Review by michaldengusiak — COMMENTED** [review]
this is an amazing function,
however it does not work as expected,
I manage to open my file and `internalize `incoming data
image

when I change boolean to False it recalculates I am losing my internalize data,
does it mean value is not stored and cut off from links how we have in GH but is still connected as a chain reaction? or we need to turn off automatic re-calculation?

let me

**Comment by awakeman** [comment]
The issue with the above appears to happen at the call to `MongoDB.Bson.BsonExtensionMethods.ToBsonDocument()` in the Serializer_Engine (Downstream of `ToJson()`).

It seems to primarily affect lists. I'll look into that and see if i can isolate the root cause.

**Comment by michaldengusiak** [comment]
@awakeman  :pray: - this would be super useful ! :wrench: :hammer:

**Comment by awakeman** [comment]
> NOTE:
> 
> #149 also raises that internalise wasn't functioning properly that i cannot reproduce. We need to be sure whether or not that is a real issue because as of yet there is no change to address that (since I couldn't reproduce to find the cause).

Worth remembering this PR doesn't claim to fix all instances of the actual internalise *functionality* failing. I have been able to reproduce now and believe it is a bug in `Serialiser_Engine` which I am investigating. However this PR is just adding the button to all the context menus as stated in the description.

I will raise an issue in the appropriate repo relating to the failure to serialise some objects when I am sure of its source.

**Comment by adecler** [comment]
@awakeman , there is a small PR that was merged a few minutes ago on the Serialiser_Engine and touches the `ToJson()` method. Might be worth recompiling your BHoM_Engine and checking if it helps.

**Comment by awakeman** [comment]
Thanks, will take a look.

**Review by FraserGreenroyd — APPROVED** [review]
LGTM - reviewed all views and can see the `Internalise Data` option on all views mentioned.

Understanding the comments of the PR, the 'bug' part of #149 will be looked into separately as it may or may not be an issue with this TK.

So on that basis, I'm happy with this.

**Pull request merged**
