### PR TITLE
Improved Excel Usage Logging

### LINKED ISSUE #357: Add Logging Functionality per New Pop-up Window
#### Description:

Making specific changes that will aide in proper implementation of BHoMAnalytics

### PR DESCRIPTION
**Pull request by travispotterBH**
New PR for branch name compliance, closes: https://github.com/BHoM/Excel_UI/pull/358
### Issues addressed by this PR

Improved logging.

Closes #357 

### Changelog

- `CallerFormula_Run.cs` - Modified to call RecordEvent() for a new ProjectIDEvent to set the project id on the usage logs

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Code review looks good, obtains a project ID from the title of the workbook for analytics where appropriate.

**Comment by travispotterBH** [comment]
@BHoMBot  check core
@BHoMBot  check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by travispotterBH** [comment]
@BHoMBot  check installer
@BHoMBot  check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
