### PR TITLE
Fix numlock being turned off

### LINKED ISSUE #238: Numlock turn off when using BHoM in Excel
#### Description:

The Numlock key turns off when filling a cell using the Ctrl-Shift-B menu.

This seems to be due to `SendKeys` having problematic interaction with Excel. See here for details and possible solution: https://stackoverflow.com/questions/25977933/sendkeys-is-messing-with-my-numlock-key-via-vba-code-in-access-form

#### Steps to reproduce:

From @BingWangUS on Teams:

> I can reproduce it with the following operations:
> - Using search to select a method.
> - Not completing the method correctly, such as not giving enough inputs.
> - Then numlock will turn off. (not switching on/off but turn off)

>Other testing:
> - Completing the method correctly does not turn off numlock.
> - Using BHoM toolbar does not have the problem

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #238 

See issue for description

### Test files
Simply follow the steps from the issue

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
I have added a `do-not-merge` while we resolve the beta patch just to make sure.

**Review by kayleighhoude — APPROVED** [review]
Fix worked for me! It was happening upon executing a BHoM compute method before, and is now not having an effect on the numlock.

**Comment by BingWangUS** [comment]
Works from my side as well.

**Comment by FraserGreenroyd** [comment]
Have removed the `do-not-merge` label, this is safe to merge when ready.

**Pull request merged**
