### PR TITLE
Update ExcelDNA to latest version

### LINKED ISSUE #334: Excel_Toolkit: Having BHoM installed appears to cause Excel to crash randomly
#### Description:

When using Excel generally with BHoM installed (although not necessarily actively using BHoM methods) I have noticed that Excel frequently freezes and has to be forced to shut down. When I uninstall BHoM the issue seems to go away.

#### Steps to reproduce:

I haven't really noticed a pattern in specific things that I did that caused the crash so can't easily reproduce the problem. Maybe there was a correlation with entering info or formulae into a cell but that's a pretty common action in Excel so unfortunately isn't very specific

#### Expected behaviour:

Excel freezes and you get the spinning blue wheel of death. Only way out I've found is to end it in Task Manager

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #334  (attempts to at least)

### Test files
N/A - per the issue, this is sporadic and hard to track down. Aim is to merge to alpha and check during alpha testing with capacity to roll back if needed.

If the BHoMBot comes back with successful checks on the key items (core, installer), then I would be happy to merge this to roll out for alpha testing.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by jamesramsden-bh — APPROVED** [review]
Not tested, confirmed as fine by Fraser, visual inspection of code looks fine.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Pull request merged**
