### PR TITLE
UI Refactoring

### LINKED ISSUE #149: Internalise Data not working in some cases
#### Description:

As above. 

#### How to replicate:

 - ~~Create a BHoM object, right click whilst in page break view, and note that the internalise data is not visible in the context menu.~~
 - When data is internalised (in normal view) the hidden sheet is created, however, the cell with the internalised data retains the formula/original entry, such that there is no reference to the internalised data. 

#### Expected behaviour:

 - ~~Internalise data should always be visible in context menu when BHoM is loaded/initialised.~~ 
 - When data is internalised, the cell contents should be replaced such that upstream/referenced changes in the spreadsheet do not cause the cell with internalised data to lose reference.

### LINKED ISSUE #187: Excel_Toolkit: BHoM Addin causes excel to re-open after quit
#### Description:
For some users, excel re-opens directly after it's closed. These users installed BHoM 3.0 after the Office 365 update, so I believe it is not related to the upgrade bug we experienced a month or two ago.

#### How to replicate:
Starting from a computer with office 365 installed and no BHoM, install BHoM 3.0 and open Excel. do stuff (non bhom) and then close excel. It will then re-open a second later.

#### Expected behaviour:
Not that

### LINKED ISSUE #218: Fix or suppress diagnostic display
#### Description:

Fix or suppress the diagnostic display - below (should we not be trying to avoid loading these - might that help load times also?). In either case, users are now contacting us as they think there is a problem so it needs sorting. 
image

### LINKED ISSUE #233: Excel_Toolkit: Excel crashing and restarting on shutdown
#### Description:

Excel still keeps on behaving weirdly. Steps taken by me today, one by one:
- installed today's installer
- opened Excel, blank workbook
- filled a few cells randomly with non-bhom content (just random strings and numbers)
- left Excel running for an hour without touching it at all
- closed Excel with upper-right cross button, refused to save the doc
- Excel looks like it is closing, but then something starts processing and the following shows up:
    image
- after 1st restart, tried to close again - restarts again
- after 2nd restart, tried to close again - success, BUT yesterday some leftover of the process was still alive and was blocking my BHoM assemblies (needed to track it down and kill via task manager -> background processes)

I am curious if that is something particular to my build or a more widespread issue.

@al-fisher @rwemay FYI

### LINKED ISSUE #240: Excel_Toolkit: Inputs Displaying As Args
#### Description:
Inputs to the object below display as "arg1" versus their actual input names.
Appears to be occurring on fragment based objects rather than normal objects (ducts appear fine)
image

### LINKED ISSUE #242: Excel_Toolkit: Display of Datasets not Consistent with Grasshopper
#### Description:

image

vs.

image

### LINKED ISSUE #244: Add call to usage log
#### Description:
Same as already done in Grasshopper. The method from BHoM_UI is `LogUsage`

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/297

   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM_UI/pull/297 for details

See comment below: https://github.com/BHoM/Excel_Toolkit/pull/243#issuecomment-678620148

Also fixes a series of pre-existing issues:
Fixes #242 
Fixes #233
Fixes #218
Fixes #187
Fixes #149
Fixes #240
Fixes #244

### CODE REVIEW

**Comment by adecler** [comment]
All right guys, this is finally ready for you to switch to this branch as your main. As before, don't use it if you are working on a critical project or if you are sharing your excel files with others as there is no forward compatibility and everyone else is still on the old version.

Note that, at this stage, I just got excel code refactored/simplified and made compatible with the new BHoM_UI repo. There is a lot to do to improve the user experience yet. Even on fundamental stuff  like memory management, execution cycles as those are super poor at the moment and I wouldn't recommend running Excel for hours without closing it. The Excel reopening at closure is unfortunately still there as well. 

On a more positive note, you'll notice a new UI section on the ribbon. At the moment, it only contains the "Internalise" button but will soon have an "expand" one as well (e.g. to expand lists). That expand functionality should also help massively simplifying the code for Explode that is still insanely scary right now (don't worry, Explode will still auto-expand without you having to use the menu button). That menu section should really help better leveraging the uniqueness of Excel. So don't hesitate to make suggestions for new buttons. 

Next week I'll work on finishing cleaning some remaining messiness in the code and will start fixing the issues mentioned above. 
This is however a good time for you to start using this new version as I think I have done all the necessary breaking changes.

**Comment by adecler** [comment]
@IsakNaslundBh , my total contribution to Excel in term of number of lines of code since the beginning of this repo is now officially negative. I told you that was quite doable :wink: 
... And  I haven't even removed the ArrayResizer monster yet 😋

**Comment by IsakNaslundBh** [comment]
Some initial testing issues. First found some issues with explode. Tried saving a testsheet [here](https://burohappold.sharepoint.com/:f:/s/BHoM/EpgUiZQGPz5Bhp63V3Ijue8BaoIUqGpj46fBUK7jNapXug?e=nRLxYP), which bring me to another issue (coming back to explode).

1. Excel crashes out when trying to open the file I saved out. The file in question sits in the folder. double clicking it, or opening it from the menu gives this:

image


2. Explode issues1. For testing I am using one of the steel libraries, "UC". Had to recreate the sheet, but will point to some errors found. Inner non-primitives are returned as `#VALUE` : 
image

3. Go deep issues. Exploding the same cell with goDeep = true gives one property name "Value, with the value being 0:

image

Will continue using and see if I can find more.

**Comment by adecler** [comment]
It looks like I have broken the saving of files somehow today. I am already way too late so I'll look into this tomorrow. '
If you go back to the commits from yesterday, that should all be working though

**Comment by AndreBalasian** [comment]
Ctrl+Shift+b is not responding. Is it possible to fix this please?

**Comment by adecler** [comment]
@IsakNaslundBh , I think I have fixed the issues you mentioned above. Let me know if you still have problems

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh , I think I have fixed the issues you mentioned above. Let me know if you still have problems

- [x] Explode to not return '#VALUE'
- [x] Explode go deep to explode inner objects
- [x] Excel to not crash on open file
- [x] Excel to load up formulas saved. Had to re-enable the method and save again in my sheet, but after doing that, all worked just fine!

So think all first issues found fixed 👍

**Comment by adecler** [comment]
OK, I think I might have finally fixed the bug with Excel crashing when closing. I say might because this thing is very elusive but I haven't had the crash for the last 10+ times I have pen Excel so that's a good sign.

The weird thing is that the bug was related to registering to the WorkbookOpened event. After a lot of trial ad errors, it sees that this version is not crashing anymore 🤞 . For the record, every detail of the change is important. Even keeping `App_WorkbookOpen` private as it was before would trigger the crash again.

Let me know if you still notice the problem after this commit. 


**Edit:** Trying to access the hidden sheet for internalised data still causes the bug (regardless of the sheet existing or not). It doesn't make sense since it is the exact same process as accessing the hidden sheet for caller but i'll just disable that for now until I found a solution to it. At least the bug doesn't occur on WorkbookOpened event anymore.

**Edit2:** Using NetOffice to try to access a sheet seems to be causing the same bug at closing time. Conclusion -> Let's get rid of that package.

**Comment by IsakNaslundBh** [comment]
have opened and closed excel ~20 times in a row now with no crash. Given the nature of the bug, that ofc does not guarantee anything, but if not gone, it at least seem to have improved it significantly!

**Comment by adecler** [comment]
**For those that have already created  new Excel spreadsheet with this PR:**

In order to add support to multiple workbooks being opened at the same time, I had to slightly modify the structure of the sheet used to save the list of used components. This mean that, while your Excel file will still open, it will not be able to execute the existing BHoM formulas correctly. 

Here's how to fix this:
- Unhide the `BHoM_CallersHidden` (right click on any sheet name and select unhide. A menu will pop up to select that sheet)
- Insert a new row at the top and write a random string
- Hide the sheet again
- Save, close and reopen the file.

image

**Review by al-fisher — APPROVED** [review]
This so LGTM!
Great stuff @adecler 
As discussed ready for wider alpha testing on master!

**Pull request merged**
