### PR TITLE
Internalise explicitly, no longer automatically.

### LINKED ISSUE #55: Excel_Toolkit: saving spreadsheet takes several minutes
Excel is unresponsive for several minutes whenever I save the sheet. Is there something in how the toolkit lets go that causes a delay?

### PR DESCRIPTION
**Pull request by awakeman**
Fixes #55

### CODE REVIEW

**Comment by awakeman** [comment]
image

**Comment by JosefTaylor** [comment]
Doesn't build- does this rely on any very recent changes upstream?

- 'Selector<T>' does not contain a definition for 'SetSelectorMenu' and no extension method 'SetSelectorMenu' accepting a first argument of type 'Selector<T>' could be found.
- cannot convert from 'Microsoft.Office.Core.CommandBarControls' to 'System.Windows.Forms.ToolStripDropDown'

**Comment by awakeman** [comment]
Yeah, it depends on some reasonably recent changes in BHoM_UI, namely BHoM/BHoM_UI#55.

**Review by JosefTaylor — APPROVED** [review]
Works great! save time is much less on my big spreadsheet.

**Pull request merged**
