### PR TITLE
Fix the versioning issues following the split

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Providing versioning starts passing then this is good to go.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by alelom — APPROVED** [review]
Approving on the bases of code changes only. Focus on versioning so ok to separate out fixing documentation.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
