### PR TITLE
Implement CreateCustom Caller

### LINKED ISSUE #59: Excel_Toolkit: Add support for CreateCustom
See https://github.com/BHoM/Excel_Toolkit/pull/54#issuecomment-453445993.

### PR DESCRIPTION
**Pull request by awakeman**
Resolves #59

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
This behaves quite differently from how it does in GH/Dynamo:

- Main use is to create custom objects with custom properties, where you can add/remove as many inputs as you like. Appreciating that this will need to behave quite differently in Excel, but something like providing a list of property names and property values could work. Think I had some very simple code for that before.
- If this solution is chosen, I think it would be good to promote this method and make it a lot more visible in the menu system.
- For the case when picking a specific object, you can in GH/Dynamo choose to remove any of the properties, as well as add any. The removing part could be solved by making all inputs optional when called through this method. Slightly different from the UI perspective, but leads to the same possibilities. Adding will be trickier, not sure right now how to solve that.

**Comment by al-fisher** [comment]
Can we confirm if a create dictionary workflow is possible in current state? i.e. create a dictionary and then pass into Sockets. This might be sufficient for now? If this is not working then this may be more Critical
@awakeman to test and post example (or not) so we can plan.

**Comment by IsakNaslundBh** [comment]
Workflow with dictionaries through sockets do not work, as the adapters require objects being pushed to be IObjects.

**Comment by awakeman** [comment]
OK, so seems the best method may be to just have the interface to match CreateDictionary and go from there. The only thing this loses is that it doesn't expose to the user what the object's properties are as it does in GH/Dynamo.

I'm thinking we could look into future helper mechanisms like an "Explode" that provides the user with the keys, ready to be populated with values. But that could be for a later date.

May attempt for now to at least show them in the Intellisense.

**Comment by al-fisher** [comment]
> OK, so seems the best method may be to just have the interface to match CreateDictionary and go from there. The only thing this loses is that it doesn't expose to the user what the object's properties are as it does in GH/Dynamo.

I agree this is a good first priority @awakeman @IsakNaslundBh - further improvements over existing properties can be added later I would say.

**Comment by IsakNaslundBh** [comment]
I think we also might want to separate this out into two different problems.

1. We need to be able to create CustomObjects in Excel. This is the most imporant part and could be solved by what has been discussed above with similar method to dictionries.

2. We want to be able to custom create any BHoMObject. Think this is what you have been trying to solve andrew. THis is also something we will want ofc, but I would say it is of less priority than the first one.

If we just can solve 1, I think that is fine for now. All we need is a method that takes a list of keys as strings and a list of objects I think we are good to go.

**Comment by awakeman** [comment]
@IsakNaslundBh That now should work with a `CreateDictionary` style interface.

**Review by IsakNaslundBh — APPROVED** [review]
Works and provides the functionality needed for this first step!

**Pull request merged**
