### PR TITLE
Remove call to UI_PostBuild.exe from post build event

### LINKED ISSUE #150: Adjust post-build events to copy just the UI specific files over
#### Broken rules:

The BHoM_UI is responsible to copy the bhom assemblies to the relative assembly folder.
Excel is now overriding this behaviour by copying the same files.
See https://github.com/BHoM/BHoM_UI/issues/103 for a bigger picture.

#### Suggestions to restore compliance:

Excel should copy just the `.gha` file and create the `.ghlink`

### PR DESCRIPTION
**Pull request by awakeman**
### Issues addressed by this PR

Closes #150 

Removes the call to the UI_PostBuild as this is handled by BHoM UI

### Test files

n/a

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Comment by epignatelli** [comment]
Guys are you sure that removing that line is enough?
How are `Excel_oM`  `Excel_Engine` and `Excel_UI` copied to `BHoM/Assemblies` now?

CI does not complain because there is no project that depends on those assemblies.

**Comment by awakeman** [comment]
By UI postbuild if the code assistant is being used, since it runs the postbuilds again. in my build the engine and oM are built before BHoM_UI too.

The CI that builds the installer uses UI_PostBuild in the installer build to get the assemblies. The bhombot based CI uses the code-assistant back-end so the same as above.

**Comment by epignatelli** [comment]
What if I compile from source instead?

**Comment by awakeman** [comment]
depends on build order i suppose. I'll add it to be sure.

**Pull request merged**
